baseURL: "http://localhost:5700"
port: 5710
database:
  mongodb:
    enable: true
    uri: mongodb://localhost/bot
    database: bot
admin:
  account: 707402933
server:
  port: 9200
  httpsPort: 9201
  
  pemPath: /etc/nginx/ssl/yibindfxy.top.pem
  keyPath: /etc/nginx/ssl/yibindfxy.top.key


